language:
  - python
python:
  - 3.5
install:
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install biopython
script:
  - py.test -vv seq_id.py --cov=seq_id
  - py.test -vv translate.py --cov=translate
  - py.test -vv adh_pipeline/accs_to_input.py --cov=accs_to_input
  - py.test -vv adh_pipeline/parse_hmm.py --cov=parse_hmm
  - py.test -vv adh_pipeline/add_accessions.py --cov=add_accessions
  - py.test -vv adh_pipeline/split_fasta_titles.py --cov=split_fasta_titles
  - py.test -vv adh_pipeline/ncbi_record.py --cov=ncbi_record
  - py.test -vv adh_pipeline/uniprot_record.py --cov=uniprot_record
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: never
