language:
  - python
python:
  - 3.5
install:
  - pip install pytest-cov
  - pip install python-coveralls
script:
  - py.test -vv seq_id.py --cov=seq_id
  - py.test -vv translate.py --cov=translate
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: never
