language:
  - python
python:
  - 3.5
install:
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install biopython
script:
  - py.test -vv seq_id.py --cov=seq_id
  - py.test -vv translate.py --cov=translate
  - py.test -vv adh_pipeline/accs_to_input.py --cov=accs_to_input
  - py.test -vv adh_pipeline/parse_hmm.py --cov=parse_hmm
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: never
